#при любом изменении файла менять тест на его загрузку
client:
  http:
    connectTimeout: "PT5S"
    requestTimeout: "PT30S"
    maxRetries: 2
    initialBackoff: "PT0.2S"
    maxBackoff: "PT2S"
    retryIdempotentOnly: true
    userAgent: "riid-client"
  auth:
    defaultTokenTtlSeconds: 300
  registries:
    - scheme: "https"
      host: "registry-1.docker.io"
      port: -1
      credentials: null

dispatcher:
  maxConcurrentRegistry: 4

